[2022-10-28 00:00:10,509] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.store_user scheduled__2022-10-27T00:00:00+00:00 [queued]>
[2022-10-28 00:00:10,515] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.store_user scheduled__2022-10-27T00:00:00+00:00 [queued]>
[2022-10-28 00:00:10,516] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-28 00:00:10,517] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-28 00:00:10,517] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-28 00:00:10,526] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): store_user> on 2022-10-27 00:00:00+00:00
[2022-10-28 00:00:10,532] {standard_task_runner.py:52} INFO - Started process 8345 to run task
[2022-10-28 00:00:10,535] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'store_user', 'scheduled__2022-10-27T00:00:00+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpqwji2xxc', '--error-file', '/tmp/tmpeh7jkaia']
[2022-10-28 00:00:10,538] {standard_task_runner.py:80} INFO - Job 40: Subtask store_user
[2022-10-28 00:00:10,581] {task_command.py:369} INFO - Running <TaskInstance: user_processing.store_user scheduled__2022-10-27T00:00:00+00:00 [running]> on host 19f0eed441f9
[2022-10-28 00:00:10,624] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2022-10-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-27T00:00:00+00:00
[2022-10-28 00:00:10,627] {postgres.py:127} INFO - Running copy expert: COPY users FROM stdin with DELIMITER as ',', filename: /tmp/processed_user.csv
[2022-10-28 00:00:10,635] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-10-28 00:00:10,645] {python.py:173} INFO - Done. Returned value was: None
[2022-10-28 00:00:10,656] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=store_user, execution_date=20221027T000000, start_date=20221028T000010, end_date=20221028T000010
[2022-10-28 00:00:10,711] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-28 00:00:10,731] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
