[2022-10-28 00:00:05,083] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-10-27T00:00:00+00:00 [queued]>
[2022-10-28 00:00:05,089] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-10-27T00:00:00+00:00 [queued]>
[2022-10-28 00:00:05,090] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-28 00:00:05,091] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-28 00:00:05,092] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-28 00:00:05,100] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-10-27 00:00:00+00:00
[2022-10-28 00:00:05,107] {standard_task_runner.py:52} INFO - Started process 8336 to run task
[2022-10-28 00:00:05,110] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2022-10-27T00:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpf0mq6oh7', '--error-file', '/tmp/tmpi3i1eue9']
[2022-10-28 00:00:05,111] {standard_task_runner.py:80} INFO - Job 37: Subtask is_api_available
[2022-10-28 00:00:05,162] {task_command.py:369} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2022-10-27T00:00:00+00:00 [running]> on host 19f0eed441f9
[2022-10-28 00:00:05,219] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-10-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-27T00:00:00+00:00
[2022-10-28 00:00:05,225] {http.py:97} INFO - Poking: api/
[2022-10-28 00:00:05,235] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-10-28 00:00:05,240] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-10-28 00:00:06,173] {base.py:301} INFO - Success criteria met. Exiting.
[2022-10-28 00:00:06,221] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20221027T000000, start_date=20221028T000005, end_date=20221028T000006
[2022-10-28 00:00:06,279] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-28 00:00:06,324] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
