[2022-10-27 13:56:01,073] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2022-10-27T13:55:59.264858+00:00 [queued]>
[2022-10-27 13:56:01,081] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2022-10-27T13:55:59.264858+00:00 [queued]>
[2022-10-27 13:56:01,082] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-27 13:56:01,083] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-27 13:56:01,084] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-27 13:56:01,095] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-10-27 13:55:59.264858+00:00
[2022-10-27 13:56:01,116] {standard_task_runner.py:52} INFO - Started process 28255 to run task
[2022-10-27 13:56:01,120] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'manual__2022-10-27T13:55:59.264858+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpbxc8bnla', '--error-file', '/tmp/tmpy8mafji0']
[2022-10-27 13:56:01,123] {standard_task_runner.py:80} INFO - Job 29: Subtask create_table
[2022-10-27 13:56:01,182] {task_command.py:369} INFO - Running <TaskInstance: user_processing.create_table manual__2022-10-27T13:55:59.264858+00:00 [running]> on host 18112c9f481e
[2022-10-27 13:56:01,250] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-10-27T13:55:59.264858+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-27T13:55:59.264858+00:00
[2022-10-27 13:56:01,261] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-10-27 13:56:01,271] {dbapi.py:208} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS users (
            firstname TEXT NOT NULL,
            lastname TEXT NOT NULL,
            country TEXT NOT NULL,
            username TEXT NOT NULL,
            password TEXT NOT NULL,
            email TEXT NOT NULL
        );
        , parameters: None
[2022-10-27 13:56:01,275] {postgres.py:94} INFO - NOTICE:  relation "users" already exists, skipping

[2022-10-27 13:56:01,284] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20221027T135559, start_date=20221027T135601, end_date=20221027T135601
[2022-10-27 13:56:01,335] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-27 13:56:01,363] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
