[2022-10-27 13:56:08,976] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.store_user manual__2022-10-27T13:55:59.264858+00:00 [queued]>
[2022-10-27 13:56:08,981] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.store_user manual__2022-10-27T13:55:59.264858+00:00 [queued]>
[2022-10-27 13:56:08,982] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-27 13:56:08,983] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-27 13:56:08,983] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-27 13:56:08,991] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): store_user> on 2022-10-27 13:55:59.264858+00:00
[2022-10-27 13:56:08,997] {standard_task_runner.py:52} INFO - Started process 28267 to run task
[2022-10-27 13:56:09,000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'store_user', 'manual__2022-10-27T13:55:59.264858+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpid0ag2p2', '--error-file', '/tmp/tmp0o3r7fxh']
[2022-10-27 13:56:09,002] {standard_task_runner.py:80} INFO - Job 33: Subtask store_user
[2022-10-27 13:56:09,042] {task_command.py:369} INFO - Running <TaskInstance: user_processing.store_user manual__2022-10-27T13:55:59.264858+00:00 [running]> on host 18112c9f481e
[2022-10-27 13:56:09,090] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2022-10-27T13:55:59.264858+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-27T13:55:59.264858+00:00
[2022-10-27 13:56:09,092] {postgres.py:127} INFO - Running copy expert: COPY users FROM stdin with DELIMITER as ',', filename: /tmp/processed_user.csv
[2022-10-27 13:56:09,099] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-10-27 13:56:09,105] {python.py:173} INFO - Done. Returned value was: None
[2022-10-27 13:56:09,113] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=store_user, execution_date=20221027T135559, start_date=20221027T135608, end_date=20221027T135609
[2022-10-27 13:56:09,134] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-27 13:56:09,154] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
