[2022-10-27 02:16:26,296] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-10-26T00:00:00+00:00 [queued]>
[2022-10-27 02:16:26,311] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-10-26T00:00:00+00:00 [queued]>
[2022-10-27 02:16:26,316] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-27 02:16:26,318] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-27 02:16:26,319] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-27 02:16:26,337] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-10-26 00:00:00+00:00
[2022-10-27 02:16:26,355] {standard_task_runner.py:52} INFO - Started process 149 to run task
[2022-10-27 02:16:26,364] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2022-10-26T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpvmpo05ua', '--error-file', '/tmp/tmpwwt2com1']
[2022-10-27 02:16:26,367] {standard_task_runner.py:80} INFO - Job 10: Subtask is_api_available
[2022-10-27 02:16:26,475] {task_command.py:369} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2022-10-26T00:00:00+00:00 [running]> on host 18112c9f481e
[2022-10-27 02:16:26,588] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-10-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-26T00:00:00+00:00
[2022-10-27 02:16:26,591] {http.py:97} INFO - Poking: api/
[2022-10-27 02:16:26,603] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-10-27 02:16:26,617] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-10-27 02:16:27,360] {base.py:301} INFO - Success criteria met. Exiting.
[2022-10-27 02:16:27,396] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20221026T000000, start_date=20221027T021626, end_date=20221027T021627
[2022-10-27 02:16:27,452] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-27 02:16:27,508] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
